Update Nodemailer production transport options for production testing
Seneca-CDOT/starchart pull request #152
Opened 2023-02-07 21:19 UTC by SerpentBytes

## Description
This PR resolves #149 by updating the `production` transport options with the following settings:
- host: `smtp.office365..com`
- port: `587`
- auth (accepts username, pass)
- requireTLS: `true  // forces STARTTLS`

2023-02-08 02:27 UTC, humphd requested changes
Nice, this is looking good.  A few small things.

2023-02-08 02:27 UTC, humphd commented on app/lib/notifications.server.ts
> +      port: Number(NOTIFICATIONS_SMTP_PORT || '587'),
This will always be `587` in production, let's not bother with a variable to configure it.

2023-02-08 02:27 UTC, humphd commented on app/lib/notifications.server.ts
>          'Missing Nodemailer environment variables or docker secrets. Skipping nodemailer configuration'
I would improve this error message: tell them which variables are actually missing, so it's easier to debug startup crashes.

2023-02-08 02:27 UTC, humphd commented on .env.example
> +NOTIFICATIONS_SMTP_PORT=587
We probably don't need this, see my comment later.

2023-02-08 02:37 UTC, SerpentBytes commented
> Nice, this is looking good.  A few small things.

I was thinking of expanding this PR by implementing tests that would work with MailHog. That way, we would know the current configuration of nodemailer is working as intended.

2023-02-08 14:40 UTC, dadolhay approved these changes

2023-02-08 19:22 UTC, sfrunza13 submitted a review, later dismissed

2023-02-08 20:48 UTC, humphd commented
@SerpentBytes looks like this is good to merge.

2023-02-09 16:38 UTC, SerpentBytes commented
> @SerpentBytes looks like this is good to merge.

merging is blocked despite have 2 approvals.

2023-02-09 16:55 UTC, shawnyu5 approved these changes

2023-02-09 17:52 UTC, humphd approved these changes

2023-02-09 17:52 UTC, humphd commented
Should be good now, I'm not sure why it blocked on my review.

2023-02-09 18:07 UTC, merged