Setup Chakra UI
Seneca-CDOT/starchart pull request #75
Opened 2023-01-31 23:09 UTC by Eakam1007

Fixes #24 

Added and setup Chakra UI. 
This does not involve the addition of a theme as there is a separate issue for it: #34 

### Steps for testing
This assumes you already have starchart [setup locally](https://github.com/Seneca-CDOT/starchart/blob/41c1e750936c604fb797b87288dc04a36992b43f/CONTRIBUTING.md#development)

- `npm install`
- `npm run dev`
- navigate to localhost:3000 and see that the app works

2023-01-31 23:45 UTC, humphd requested changes
This looks good.

Can you modify something in the https://github.com/Seneca-CDOT/starchart/blob/main/app/routes/index.tsx to use ChakraUI Components?  Maybe switch to:

- https://chakra-ui.com/docs/components/heading
- https://chakra-ui.com/docs/components/text

That will make it easier for others to test that this works.

2023-02-01 00:21 UTC, Myrfion approved these changes
Agree with @humphd on adding some simple Charka components on `index.tsx` to show everybody else how it works, other than that LGTM

2023-02-01 01:31 UTC, Eakam1007 commented
I changed the index page to use the components you linked. I also added some styles to change the font size so the change should be visible now

2023-02-01 02:11 UTC, humphd approved these changes

2023-02-01 14:08 UTC, dadolhay approved these changes

2023-02-01 17:07 UTC, merged