Adding login and logout as starchart user from initial seed
Seneca-CDOT/starchart pull request #88
Opened 2023-02-02 15:29 UTC by sfrunza13

Closes #22
Adding login page with login button that signs you (creates a session as per the session server that came with blues stack) in as the user that we seed username:"starchartdev".

2023-02-02 18:19 UTC, humphd requested changes
This is looking good.  A few things to use newer code, and also you'll need to rebase to get the changes to `index.tsx`

2023-02-02 18:19 UTC, humphd commented on app/routes/index.tsx
> +  return json({ username: username });
nit: when the key/value are the same, include it only once:

```ts
return json({ username });
```

2023-02-02 18:19 UTC, humphd commented on app/routes/index.tsx
> +      <p>{data.username}</p>
Let's use [Chakra UI components](https://chakra-ui.com/docs/components) and [Remix's `<Form>` component](https://remix.run/docs/en/v1/components/form).  Here's a suggestion:

```tsx
<Text>Welcome {data.username}</Text>
<Form action="/logout" method="post">
  <Button type="submit" colorScheme="red">Logout</button>
</Form>
```

2023-02-02 18:19 UTC, humphd commented on app/routes/login.tsx
> +      <h1>Login</h1>
```tsx
<Button type="submit" colorScheme="red">Login</button>
```

2023-02-02 19:57 UTC, sfrunza13 commented
> This is looking good. A few things to use newer code, and also you'll need to rebase to get the changes to `index.tsx`

How's it now?

2023-02-02 21:35 UTC, humphd requested changes

2023-02-02 21:35 UTC, humphd commented on app/routes/index.tsx
> +import { json, LoaderArgs } from "@remix-run/node";
`LoaderArgs` is being imported as a type, so you separate it from your other imports and use `import type`.  You do it like this:

```ts
import { json } from "@remix-run/node";

import type { LoaderArgs } from "@remix-run/node";
```

2023-02-02 21:35 UTC, humphd commented on app/routes/index.tsx
> +      <form action="/logout" method="post">
`<form>` is HTML, you want `<Form>` from Remix.

2023-02-02 21:35 UTC, humphd commented on app/routes/login.tsx
> +import { ActionArgs } from "@remix-run/node";
Same with this: move to a new line, `import type ...`

2023-02-02 21:43 UTC, sfrunza13 commented
Hopefully that does it

2023-02-02 21:43 UTC, humphd requested changes

2023-02-02 21:43 UTC, humphd commented on app/routes/index.tsx
> +import type { LoaderArgs } from "@remix-run/node";
Move your type imports below your regular imports and separate with a blank line:

```ts
import {...} from "..."
import {...} from "..."

import type {...} from "..."
import type {...} from "..."
```

2023-02-02 21:43 UTC, humphd commented on app/routes/login.tsx
> +import type { ActionArgs } from "@remix-run/node";
Same thing here.

2023-02-02 21:52 UTC, sfrunza13 commented
I put the types under other imports and squashed, unfortunately realized I had not ordered things right in the logout and added another commit to fix the order of the imports there too

2023-02-02 21:58 UTC, humphd commented
You have conflicts in `app/routes/index.tsx`, you need to rebase and fix.

2023-02-02 22:22 UTC, sfrunza13 commented
> You have conflicts in `app/routes/index.tsx`, you need to rebase and fix.

is it correct to do as I am doing and pull upstream into origin main, then checkout my feature branch and rebase main and force push?

2023-02-02 22:28 UTC, humphd commented
```
git checkout main
git pull upstream main
git checkout your-branch
git rebase main
git push origin your-branch -f
```

2023-02-02 22:29 UTC, sfrunza13 commented
Cool, that's what I did :D

2023-02-02 22:30 UTC, humphd approved these changes

2023-02-02 22:30 UTC, sfrunza13 commented
and after all that's done and changes are approved is it ok to just hit squash and merge here in the PR?

2023-02-02 22:30 UTC, humphd commented
Not sure why Prettier is failing here, but your code changes look good.

2023-02-02 22:34 UTC, sfrunza13 commented
> Not sure why Prettier is failing here, but your code changes look good.

this has made me realize there was a format script to rewrite with prettier before my last rebase and now there isn't

2023-02-02 23:43 UTC, Eakam1007 commented
Looks good. Before merging, you can use `npx prettier --write .` to rewrite with prettier

2023-02-02 23:53 UTC, Eakam1007 approved these changes
Looks good! 
Is there an issue to add end-to-end tests for this once #85 is merged? This page will likely change in the future but I think we should start adding tests early

2023-02-02 23:55 UTC, sfrunza13 commented
> Looks good! Is there an issue to add end-to-end tests for these pages once #85 is merged? This page will likely change in the future but I think we should start adding tests early

I'll have to learn how to write one but I think I could probably do it :)

2023-02-02 23:56 UTC, Eakam1007 commented
> I'll have to learn how to write one but I think I could probably do it :)

That's perfect! Do you wanna create an issue for the tests?

2023-02-03 00:00 UTC, sfrunza13 commented
> > I'll have to learn how to write one but I think I could probably do it :)
> 
> That's perfect! Do you wanna create an issue for the tests?

not super descriptive but #98

2023-02-03 02:19 UTC, humphd approved these changes
Nice work, this looks great.  I'm excited to see the auth happening so soon!

2023-02-03 04:12 UTC, merged